# The default configuration file.
# Syntax in `private_pgt/settings/settings.py`
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: true
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]
  base_url: http://localhost:8001

database:
  name: test

token:
  secret_key: wizzard
  admin_key: admin