# The default configuration file.
# Syntax in `private_pgt/settings/settings.py`
server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}
  cors:
    enabled: false
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_headers: ["*"]

token:
  secret_key: wizzard
  admin_key: admin
  
database:
  name: test

data:
  photo_data_folder: photos
  processed_data_folder: processed

